# Shopify CLI configuration to prevent URL changes
tunnel_url: "https://announcement-bar-app-dev.trycloudflare.com"
dev_store: "selya11904.myshopify.com"

# App settings
app:
  application_url: "https://announcement-bar-app-dev.trycloudflare.com"
  force_https: true
  
# Development settings  
development:
  tunnel_provider: "cloudflare"
  tunnel_auth: false
  
# Prevent URL regeneration
config:
  analytics: false
  auto_update_urls: false


