app = "announcement-bar-app-lqjqja"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  SHOPIFY_APP_URL = "https://announcement-bar-app-lqjqja.fly.dev"
  HOST = "announcement-bar-app-lqjqja.fly.dev"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
